-- Optional starter seed for official MET activities.
-- Source: 2024 Adult Compendium of Physical Activities.
-- Run after schema.sql in pgAdmin.

INSERT INTO activities (
    name,
    met_multiplier,
    category,
    source,
    source_type,
    external_id,
    source_url,
    met_source_code,
    met_source_description,
    met_estimation_method
) VALUES
('Aerobic general', 7.3, 'Cardio', 'Compendium', '2024 Adult Compendium of Physical Activities', '02000', 'https://pacompendium.com/conditioning-exercise/', '02000', 'Aerobic, general', 'official_compendium'),
('Aerobic step treaptă joasă', 5.5, 'Cardio', 'Compendium', '2024 Adult Compendium of Physical Activities', '02001', 'https://pacompendium.com/conditioning-exercise/', '02001', 'Aerobic, step, with 4-inch step', 'official_compendium'),
('Aerobic step treaptă înaltă', 9.0, 'Cardio', 'Compendium', '2024 Adult Compendium of Physical Activities', '02003', 'https://pacompendium.com/conditioning-exercise/', '02003', 'Aerobic, step, with 10 - 12 inch step', 'official_compendium'),
('Dans aerobic moderat', 4.8, 'Cardio', 'Compendium', '2024 Adult Compendium of Physical Activities', '02005', 'https://pacompendium.com/conditioning-exercise/', '02005', 'Aerobic dance, low impact, moderate effort', 'official_compendium'),
('Dans aerobic intens', 8.0, 'Cardio', 'Compendium', '2024 Adult Compendium of Physical Activities', '02006', 'https://pacompendium.com/conditioning-exercise/', '02006', 'Aerobic dance, high impact, vigorous effort', 'official_compendium'),
('Calistenice intense', 7.5, 'Forță', 'Compendium', '2024 Adult Compendium of Physical Activities', '02020', 'https://pacompendium.com/conditioning-exercise/', '02020', 'Calisthenics vigorous effort', 'official_compendium'),
('Calistenice moderate', 3.8, 'Forță', 'Compendium', '2024 Adult Compendium of Physical Activities', '02022', 'https://pacompendium.com/conditioning-exercise/', '02022', 'Calisthenics moderate effort', 'official_compendium'),
('Calistenice ușoare', 2.8, 'Forță', 'Compendium', '2024 Adult Compendium of Physical Activities', '02024', 'https://pacompendium.com/conditioning-exercise/', '02024', 'Calisthenics light effort', 'official_compendium'),
('Circuit cu greutatea corpului', 6.0, 'Forță', 'Compendium', '2024 Adult Compendium of Physical Activities', '02032', 'https://pacompendium.com/conditioning-exercise/', '02032', 'Circuit training, body weight exercises', 'official_compendium'),
('Circuit training moderat', 5.0, 'Forță', 'Compendium', '2024 Adult Compendium of Physical Activities', '02035', 'https://pacompendium.com/conditioning-exercise/', '02035', 'Circuit training, moderate effort', 'official_compendium'),
('Circuit kettlebell intens', 7.5, 'Forță', 'Compendium', '2024 Adult Compendium of Physical Activities', '02040', 'https://pacompendium.com/conditioning-exercise/', '02040', 'Circuit training, including kettlebells, vigorous intensity', 'official_compendium'),
('Eliptică moderată', 5.0, 'Cardio', 'Compendium', '2024 Adult Compendium of Physical Activities', '02048', 'https://pacompendium.com/conditioning-exercise/', '02048', 'Elliptical trainer, moderate effort', 'official_compendium'),
('Eliptică intensă', 9.0, 'Cardio', 'Compendium', '2024 Adult Compendium of Physical Activities', '02049', 'https://pacompendium.com/conditioning-exercise/', '02049', 'Elliptical trainer, vigorous effort', 'official_compendium'),
('Ridicare greutăți intensă', 6.0, 'Forță', 'Compendium', '2024 Adult Compendium of Physical Activities', '02050', 'https://pacompendium.com/conditioning-exercise/', '02050', 'Resistance weight lifting, vigorous effort', 'official_compendium'),
('Genuflexiuni sau îndreptări cu greutăți', 5.0, 'Forță', 'Compendium', '2024 Adult Compendium of Physical Activities', '02052', 'https://pacompendium.com/conditioning-exercise/', '02052', 'Resistance weight training, squats, deadlift', 'official_compendium'),
('Antrenament cu greutăți general', 3.5, 'Forță', 'Compendium', '2024 Adult Compendium of Physical Activities', '02054', 'https://pacompendium.com/conditioning-exercise/', '02054', 'Resistance weight training, multiple exercises, 8-15 reps', 'official_compendium'),
('Antrenament cu greutatea corpului general', 3.0, 'Forță', 'Compendium', '2024 Adult Compendium of Physical Activities', '02056', 'https://pacompendium.com/conditioning-exercise/', '02056', 'Body weight resistance exercises, general', 'official_compendium'),
('Antrenament cu greutatea corpului intens', 6.5, 'Forță', 'Compendium', '2024 Adult Compendium of Physical Activities', '02057', 'https://pacompendium.com/conditioning-exercise/', '02057', 'Body weight resistance exercises, high intensity', 'official_compendium'),
('Kettlebell swings', 9.8, 'Forță', 'Compendium', '2024 Adult Compendium of Physical Activities', '02058', 'https://pacompendium.com/conditioning-exercise/', '02058', 'Kettlebell swings', 'official_compendium'),
('Exerciții la sală general', 5.5, 'Forță', 'Compendium', '2024 Adult Compendium of Physical Activities', '02060', 'https://pacompendium.com/conditioning-exercise/', '02060', 'Health club exercise, general', 'official_compendium'),
('Bandă de scări', 9.3, 'Cardio', 'Compendium', '2024 Adult Compendium of Physical Activities', '02065', 'https://pacompendium.com/conditioning-exercise/', '02065', 'Stair treadmill ergometer, general', 'official_compendium'),
('Sărit coarda general', 11.0, 'Cardio', 'Compendium', '2024 Adult Compendium of Physical Activities', '02068', 'https://pacompendium.com/conditioning-exercise/', '02068', 'Rope skipping exercise, general', 'official_compendium'),
('Canotaj ergometru moderat', 5.0, 'Cardio', 'Compendium', '2024 Adult Compendium of Physical Activities', '02071', 'https://pacompendium.com/conditioning-exercise/', '02071', 'Rowing, stationary ergometer, moderate effort', 'official_compendium'),
('Canotaj ergometru intens', 7.3, 'Cardio', 'Compendium', '2024 Adult Compendium of Physical Activities', '02070', 'https://pacompendium.com/conditioning-exercise/', '02070', 'Rowing, stationary ergometer, vigorous effort', 'official_compendium'),
('Stretching ușor', 2.3, 'Flexibilitate', 'Compendium', '2024 Adult Compendium of Physical Activities', '02101', 'https://pacompendium.com/conditioning-exercise/', '02101', 'Stretching, mild', 'official_compendium'),
('Pilates la saltea', 1.8, 'Flexibilitate', 'Compendium', '2024 Adult Compendium of Physical Activities', '02103', 'https://pacompendium.com/conditioning-exercise/', '02103', 'Pilates, traditional, mat', 'official_compendium'),
('Pilates general', 2.8, 'Flexibilitate', 'Compendium', '2024 Adult Compendium of Physical Activities', '02105', 'https://pacompendium.com/conditioning-exercise/', '02105', 'Pilates, general', 'official_compendium'),
('Yoga Hatha', 2.3, 'Flexibilitate', 'Compendium', '2024 Adult Compendium of Physical Activities', '02150', 'https://pacompendium.com/conditioning-exercise/', '02150', 'Yoga, Hatha', 'official_compendium'),
('Yoga Power', 4.0, 'Flexibilitate', 'Compendium', '2024 Adult Compendium of Physical Activities', '02160', 'https://pacompendium.com/conditioning-exercise/', '02160', 'Yoga, Power', 'official_compendium'),
('HIIT moderat', 7.0, 'Cardio', 'Compendium', '2024 Adult Compendium of Physical Activities', '02210', 'https://pacompendium.com/conditioning-exercise/', '02210', 'High intensity interval exercise, moderate effort', 'official_compendium'),
('HIIT intens', 11.0, 'Cardio', 'Compendium', '2024 Adult Compendium of Physical Activities', '02214', 'https://pacompendium.com/conditioning-exercise/', '02214', 'High intensity interval exercise, vigorous effort', 'official_compendium'),
('Zumba clasă de grup', 6.5, 'Cardio', 'Compendium', '2024 Adult Compendium of Physical Activities', '02310', 'https://pacompendium.com/conditioning-exercise/', '02310', 'Zumba, group class', 'official_compendium'),
('Ciclism recreațional sub 16 km/h', 4.0, 'Cardio', 'Compendium', '2024 Adult Compendium of Physical Activities', '01010', 'https://pacompendium.com/bicycling/', '01010', 'Bicycling, <10 mph, leisure', 'official_compendium'),
('Ciclism general', 7.0, 'Cardio', 'Compendium', '2024 Adult Compendium of Physical Activities', '01014', 'https://pacompendium.com/bicycling/', '01014', 'Bicycling, general', 'official_compendium'),
('Ciclism 16-19 km/h', 6.8, 'Cardio', 'Compendium', '2024 Adult Compendium of Physical Activities', '01020', 'https://pacompendium.com/bicycling/', '01020', 'Bicycling, 10-11.9 mph, slow, light effort', 'official_compendium'),
('Ciclism 19-22 km/h', 8.0, 'Cardio', 'Compendium', '2024 Adult Compendium of Physical Activities', '01030', 'https://pacompendium.com/bicycling/', '01030', 'Bicycling, 12-13.9 mph, moderate effort', 'official_compendium'),
('Ciclism 23-25 km/h', 10.0, 'Cardio', 'Compendium', '2024 Adult Compendium of Physical Activities', '01040', 'https://pacompendium.com/bicycling/', '01040', 'Bicycling, 14-15.9 mph, fast, vigorous effort', 'official_compendium'),
('Bicicletă staționară ușoară', 4.0, 'Cardio', 'Compendium', '2024 Adult Compendium of Physical Activities', '01214', 'https://pacompendium.com/bicycling/', '01214', 'Bicycling, stationary, 50 watts, light effort', 'official_compendium'),
('Bicicletă staționară moderată', 6.0, 'Cardio', 'Compendium', '2024 Adult Compendium of Physical Activities', '01220', 'https://pacompendium.com/bicycling/', '01220', 'Bicycling, stationary, 90-100 watts, moderate to vigorous', 'official_compendium'),
('Clasă spinning', 9.0, 'Cardio', 'Compendium', '2024 Adult Compendium of Physical Activities', '01270', 'https://pacompendium.com/bicycling/', '01270', 'Bicycling, stationary, RPM/Spin bike class', 'official_compendium'),
('Alergare ușoară generală', 7.5, 'Cardio', 'Compendium', '2024 Adult Compendium of Physical Activities', '12020', 'https://pacompendium.com/running/', '12020', 'Jogging, general, self-selected pace', 'official_compendium'),
('Alergare pe loc', 4.8, 'Cardio', 'Compendium', '2024 Adult Compendium of Physical Activities', '12025', 'https://pacompendium.com/running/', '12025', 'Jogging, in place', 'official_compendium'),
('Alergare 8 km/h', 8.5, 'Cardio', 'Compendium', '2024 Adult Compendium of Physical Activities', '12030', 'https://pacompendium.com/running/', '12030', 'Running, 5.0 to 5.2 mph', 'official_compendium'),
('Alergare 9-10 km/h', 9.3, 'Cardio', 'Compendium', '2024 Adult Compendium of Physical Activities', '12050', 'https://pacompendium.com/running/', '12050', 'Running, 6-6.3 mph', 'official_compendium'),
('Alergare 11 km/h', 11.0, 'Cardio', 'Compendium', '2024 Adult Compendium of Physical Activities', '12070', 'https://pacompendium.com/running/', '12070', 'Running, 7 mph', 'official_compendium'),
('Alergare cross-country', 9.3, 'Cardio', 'Compendium', '2024 Adult Compendium of Physical Activities', '12140', 'https://pacompendium.com/running/', '12140', 'Running, cross country', 'official_compendium'),
('Alergare pe scări', 15.0, 'Cardio', 'Compendium', '2024 Adult Compendium of Physical Activities', '12170', 'https://pacompendium.com/running/', '12170', 'Running, stairs, up', 'official_compendium'),
('Mers lent', 2.8, 'Cardio', 'Compendium', '2024 Adult Compendium of Physical Activities', '17152', 'https://pacompendium.com/walking/', '17152', 'Walking, 2.0 to 2.4 mph, slow pace', 'official_compendium'),
('Mers de plăcere', 3.5, 'Cardio', 'Compendium', '2024 Adult Compendium of Physical Activities', '17160', 'https://pacompendium.com/walking/', '17160', 'Walking for pleasure', 'official_compendium'),
('Plimbare cu câinele', 3.0, 'Cardio', 'Compendium', '2024 Adult Compendium of Physical Activities', '17165', 'https://pacompendium.com/walking/', '17165', 'Walking the dog', 'official_compendium'),
('Mers moderat', 3.8, 'Cardio', 'Compendium', '2024 Adult Compendium of Physical Activities', '17190', 'https://pacompendium.com/walking/', '17190', 'Walking, moderate pace', 'official_compendium'),
('Mers alert', 4.8, 'Cardio', 'Compendium', '2024 Adult Compendium of Physical Activities', '17200', 'https://pacompendium.com/walking/', '17200', 'Walking, brisk, firm surface', 'official_compendium'),
('Mers foarte alert', 5.5, 'Cardio', 'Compendium', '2024 Adult Compendium of Physical Activities', '17220', 'https://pacompendium.com/walking/', '17220', 'Walking, very brisk pace', 'official_compendium'),
('Drumeție cross-country', 6.0, 'Cardio', 'Compendium', '2024 Adult Compendium of Physical Activities', '17080', 'https://pacompendium.com/walking/', '17080', 'Hiking, cross country', 'official_compendium'),
('Urcat scări general', 6.8, 'Cardio', 'Compendium', '2024 Adult Compendium of Physical Activities', '17131', 'https://pacompendium.com/walking/', '17131', 'Stair climbing, general', 'official_compendium'),
('Baschet meci', 8.0, 'Sport de echipă', 'Compendium', '2024 Adult Compendium of Physical Activities', '15040', 'https://pacompendium.com/sports/', '15040', 'Basketball, game', 'official_compendium'),
('Baschet aruncări la coș', 5.0, 'Sport de echipă', 'Compendium', '2024 Adult Compendium of Physical Activities', '15070', 'https://pacompendium.com/sports/', '15070', 'Basketball, shooting baskets', 'official_compendium'),
('Fotbal recreațional', 7.0, 'Sport de echipă', 'Compendium', '2024 Adult Compendium of Physical Activities', '15610', 'https://pacompendium.com/sports/', '15610', 'Soccer, casual, general', 'official_compendium'),
('Fotbal competitiv', 9.5, 'Sport de echipă', 'Compendium', '2024 Adult Compendium of Physical Activities', '15605', 'https://pacompendium.com/sports/', '15605', 'Soccer, competitive', 'official_compendium'),
('Tenis simplu', 8.0, 'Sport de echipă', 'Compendium', '2024 Adult Compendium of Physical Activities', '15690', 'https://pacompendium.com/sports/', '15690', 'Tennis, singles', 'official_compendium'),
('Tenis dublu', 6.0, 'Sport de echipă', 'Compendium', '2024 Adult Compendium of Physical Activities', '15680', 'https://pacompendium.com/sports/', '15680', 'Tennis, doubles', 'official_compendium'),
('Volei recreațional', 4.0, 'Sport de echipă', 'Compendium', '2024 Adult Compendium of Physical Activities', '15710', 'https://pacompendium.com/sports/', '15710', 'Volleyball', 'official_compendium'),
('Volei pe plajă', 8.0, 'Sport de echipă', 'Compendium', '2024 Adult Compendium of Physical Activities', '15725', 'https://pacompendium.com/sports/', '15725', 'Volleyball, beach', 'official_compendium'),
('Înot liber rapid', 9.8, 'Cardio', 'Compendium', '2024 Adult Compendium of Physical Activities', '18230', 'https://pacompendium.com/water-activities/', '18230', 'Swimming laps, freestyle, fast, vigorous effort', 'official_compendium'),
('Înot liber lent', 5.8, 'Cardio', 'Compendium', '2024 Adult Compendium of Physical Activities', '18240', 'https://pacompendium.com/water-activities/', '18240', 'Swimming laps, freestyle, slow, recreational', 'official_compendium'),
('Înot bras recreațional', 5.3, 'Cardio', 'Compendium', '2024 Adult Compendium of Physical Activities', '18265', 'https://pacompendium.com/water-activities/', '18265', 'Swimming breaststroke, recreational', 'official_compendium'),
('Aquagym', 5.5, 'Cardio', 'Compendium', '2024 Adult Compendium of Physical Activities', '18355', 'https://pacompendium.com/water-activities/', '18355', 'Water aerobics, water calisthenics, general', 'official_compendium')
ON CONFLICT (source, external_id) DO UPDATE SET
    name = EXCLUDED.name,
    met_multiplier = EXCLUDED.met_multiplier,
    category = EXCLUDED.category,
    source_type = EXCLUDED.source_type,
    source_url = EXCLUDED.source_url,
    met_source_code = EXCLUDED.met_source_code,
    met_source_description = EXCLUDED.met_source_description,
    met_estimation_method = EXCLUDED.met_estimation_method;
